version: '3.9'

services:
  database:
    image: mysql
    platform: linux/x86_64
    container_name: adonis-api-database
    command: --authentication_policy=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'adonis-sql'
    ports:
      - '3306:3306'
